name: Release

permissions:
  contents: write

on: 
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  release:
    name: Create GitHub release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install parse-changelog
        uses: taiki-e/install-action@v2
        with:
          tool: parse-changelog

      - name: Generate release notes
        run: parse-changelog ${{ github.workspace }}/CHANGELOG.md > ${{ github.workspace }}-release_notes.md

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/_deploy/artifacts # This will store all artifacts in separate folders

      - name: Consolidate artifacts
        run: |
          mkdir -p ${{ github.workspace }}/_deploy/consolidated
          find ${{ github.workspace }}/_deploy/artifacts -type f -exec mv {} ${{ github.workspace }}/_deploy/consolidated/ \;

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.download.outputs.download-path }}/*
          draft: true
          body_path: ${{ github.workspace }}-release_notes.md
